#!/bin/sh
## show disk space usage for directories in $1
if [ `uname` = "Darwin" ] ; then
    /opt/homebrew/opt/coreutils/libexec/gnubin/du -h --max-depth=1 "$@"
else
    du -h --max-depth=1 "$@"
fi


