#!/bin/bash

if [ ! -n "$1" ] ; then
    echo "Usage: $(basename $0) url"
    exit 1
fi

for PAGE in $* ; do
    echo "getting page $PAGE"

    OUTPUT=$(wget -O - $PAGE)

    echo $OUTPUT
    if echo $OUTPUT | grep -o "http://[^\'\"]*flv" ; then
	echo "flv found"
	wget $(echo $OUTPUT | grep -o http://[^\'\"]*flv | sort | uniq)
#elif echo $OUTPUT | grep -o "[^\"]+wmv" ; then
    elif echo $OUTPUT | egrep -o "[^\"]+wmv" ; then
	for MATCH in $(echo $OUTPUT | egrep -o "[^\"]+wmv") ; do
	    
	    wget "$(dirname $PAGE)/$MATCH"
	done
    else
	echo "no luck"
    fi
#wget $(wget -O - $1 | grep -o http://[^\'\"]*flv | sort | uniq)
    echo "Finished page $PAGE"
done

echo "All done"