#!/bin/bash

if [ -n "$1" ] ; then
    if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "--usage" ] ; then
	echo "Converts all pdfs in pwd to ps and sends them to the printer"
	exit 1
    fi
fi

for FILE in "$@"
  do
  if echo "$FILE" | grep -q .pdf ; then
      echo "Acrobat is converting $FILE to PostScript"
      acroread -toPostScript "$FILE" > /dev/null 2>&1
      PSFILE=$(echo "$FILE" | sed -e 's/.pdf/.ps/')
      echo "Formatting $PSFILE and sending to the printer"
      psnup -2 "$PSFILE" | lpr
  else
      echo "$FILE is not a pdf file, skipping"
  fi
done
