#!/usr/bin/perl

use warnings;
use strict;

# checkspelling - check the spelling of a word

my $spell_program="ispell -a";

if ( @ARGV <  1 )
{

    $0 =~ m{([^/]*$)};
    my $name = $1;
    print "Usage: $name word or words\n";
    exit 1
}

my $words = join (' ', @ARGV);

my $output = `echo $words | $spell_program`;
my $word = "";
while ($output =~ /(.+)/g)
{
    $word = $1;
    if ($word =~ /^&/)
    {
	$word =~ /& (\w+).*: (.*)/;
	print "Unkown word: '$1' \n";
	print "Suggestions: $2 \n";
	print "---------------------------\n";
    }
    elsif ($word =~ /^#/)
    {
	$word =~ /# (\w+)/;
	print "Unknown word: '$1'\n";
	print "No suggestions!\n";
	print "---------------------------\n";
    }
    elsif ($word =~ /^[\*|@]/)
    {
	#beginning output and correctly spelled word. Just ignore
    }
    else
    {
	print "Unhandled output\n$word\n";
    }

}



