#!/bin/sh

# This will show the time and the current battery state so that
# I can see how much battery power is used in ram suspend

echo "Hibernate started at $(date)"
echo "Current battery state"
cat /proc/acpi/battery/BAT0/state
su -c hibernate-ram
echo "Resumed at $(date)"
echo "Current battery state"
cat /proc/acpi/battery/BAT0/state


# 200 mWh drained in 16:24

# 760 mWh drained in 