#!/bin/zsh

set -e
setopt EXTENDED_GLOB

#############################################################
##
## Detect and set environment
##
############################################################# 

if [ -f "${HOME}/.work" ] ; then
    HOME_ENV=false
    WORK_ENV=true
elif [ -f "${HOME}/.home" ] ; then
    HOME_ENV=true
    WORK_ENV=false
else
    ENV_CHOICE=""
    while [ "$ENV_CHOICE" != "home" ] && [ "$ENV_CHOICE" != "work" ] ; do
        echo "Is this a home or work machine? (home/work)"
        read ENV_CHOICE
    done
    if [ "$ENV_CHOICE" = "home" ] ; then
        touch "${HOME}/.home"
        HOME_ENV=true
        WORK_ENV=false
    else
        touch "${HOME}/.work"
        HOME_ENV=false
        WORK_ENV=true
    fi
fi

if [ "$1" = "upgrade" ] ; then
    UPGRADE=true
    BUNDLE_ARGS=("--quiet")
else
    UPGRADE=false
    BUNDLE_ARGS=("--no-upgrade" "--quiet")
fi

function run_brew_bundle() {
    local FILE=$1
    if [ -f "$FILE" ] ; then
        echo "Running brew bundle for $FILE"
        brew bundle install "${BUNDLE_ARGS[@]}" --file="$FILE"
    fi
}


JJR_HOME="${HOME}/.dotfiles"
HUBSPOT_KICKSTART="${HOME}/.hubspot-kickstart-run-by-jjr-env-setup"

#############################################################
##
## Functions
##
############################################################# 

function link_home_dir(){
    pushd ~
    local RESOURCE=false
    if [ ! -d "${JJR_HOME}" ] ; then
        echo "It looks like your dotfiles aren't here yet. Go get them from https://github.com/jjrussell/dotfiles"
        exit 1
    fi
    for DOT in `ls -A ${JJR_HOME}` ; do
        if [ ! "${DOT}" = ".git" ] ; then
            if [ -e ${HOME}/$DOT ] && [ ! -h ${HOME}/$DOT ] ; then # exists and isn't already a symlink
                mv -v ${HOME}/$DOT ${HOME}/$DOT.orig
                RESOURCE=true
            fi
            ln -sf ${JJR_HOME}/$DOT . # this will clobber all existing symlinks so the command is idempotent
        fi
    done
    if $RESOURCE ; then
        echo "Re-source dot files and rerun this command: $0"
        exit 1
    fi
    
    popd > /dev/null
    echo "Home directory linked"
}

function install_zprezto(){
    if [ ! -d "${JJR_HOME}/.zprezto" ] ; then
        echo "Installing .zprezto"
        git clone --recursive https://github.com/sorin-ionescu/prezto.git "${JJR_HOME}/.zprezto"

        for rcfile in "${JJR_HOME}"/.zprezto/runcoms/^README.md(.N); do
            ln -sf "$rcfile" "${JJR_HOME}/.${rcfile:t}"
        done
    fi

}

function install_homebrew(){
    if ! which brew > /dev/null ; then
        echo "Going to install homebrew now"
        echo "http://brew.sh/"
        echo "Going to execute the brew install script from https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
        echo "Enter to proceed"
        echo "Ctrl-C to exit"
        read
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    fi
}


function install_ruby() {
    # rbenv and ruby-build are in the Brewfile
    if ! rbenv versions | grep -q .; then
        rbenv install -l | grep -E '^\s*[0-9]+\.[0-9]+\.[0-9]+$' | tail -1 | xargs rbenv install
        rbenv global $(rbenv versions --bare | tail -1)
    fi
}


function install_emacs() {
    # emacs-plus and duti are in the Brewfile
    if [ -d /opt/homebrew/Cellar/emacs-plus@30/*/Emacs.app ] && [ ! -e /Applications/Emacs.app ] ; then
        cp -R /opt/homebrew/Cellar/emacs-plus@30/*/Emacs.app /Applications/Emacs.app
    fi
    
    if [ ! -d ~/.emacs.d ] ; then
        echo "Pulling latest emacs.d from github and installing emacs"
        pushd ~
        git clone git@github.com:jjrussell/emacs.d.git .emacs.d
        popd
    fi

    # EmacsClient.app - a compiled AppleScript wrapper around emacsclient
    # that opens files in the existing Emacs frame instead of spawning a new one.
    # Used as the default macOS handler for text/source files.
    if [ -d "${HOME}/.bin/EmacsClient.app" ] ; then
        ln -sfv ${HOME}/.bin/EmacsClient.app /Applications/EmacsClient.app
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/EmacsClient.app
        for ext in .el .py .js .ts .tsx .jsx .java .rb .rs .go .c .h .cpp .sh .zsh .bash .yml .yaml .json .toml .xml .css .scss .sql .md .txt .cfg .conf .ini .log .org; do
            duti -s org.gnu.emacsclient "$ext" editor
        done
        duti -s org.gnu.emacsclient public.plain-text editor
        duti -s org.gnu.emacsclient public.source-code editor
        duti -s org.gnu.emacsclient net.daringfireball.markdown editor
        echo "EmacsClient.app linked and set as default editor for common file types"
    fi

}

function mac_settings(){
    echo "OSX specific settings"
    # faster key repeats. Usually have to log out and log in to take effect
    # normal minimum is 15 (225 ms)
    defaults write -g InitialKeyRepeat -int 10 
    # or 0
    defaults write -g KeyRepeat -int 1

    # When I press a key, repeat the key, don't show other character sets
    defaults write -g ApplePressAndHoldEnabled -bool false

    # echo "Overlaying the directory structure backed up by jjr-env-backup onto the OSX config directories"

}


# function install_xcode(){
#     if [ -d "/Applications/Xcode.app" ] ; then
#         if ! which xcodebuild 2>&1 > /dev/null ; then
#             sudo xcodebuild -license
#             xcode-select --install
#         fi
#     else
#         echo "Xcode is, like, required and stuff. Go install it."
#         open -a "App Store"
#         exit 1
#     fi
# }

# Do whatever needs doing for wherever work is 
function work_setup(){
    echo "Running work setup"
    if [ ! -e "$HUBSPOT_KICKSTART" ] ; then
        echo "executing HubSpot kickstart script https://private.hubteam.com/kickstart/start.sh"
        echo "Enter to proceed, Ctrl-C to stop"
        read
        sh -c "$(curl --fail https://private.hubteam.com/kickstart/start.sh)"
        touch "$HUBSPOT_KICKSTART"
    else
        echo "HubSpot kickstart already run. Skipping"
        echo "To run it again delete $HUBSPOT_KICKSTART"
    fi
}

# End of function definitions

#############################################################
##
## Do the thing
##
############################################################# 

if ${WORK_ENV} ; then
    work_setup
fi

if [ ! -d ${JJR_HOME} ] ; then
    echo "Your home env directory ${JJR_HOME} wasn't there"
    echo "git clone git@github.com:jjrussell/dotfiles.git"
    exit 1
fi

install_homebrew
install_zprezto
link_home_dir
mac_settings

echo "Running brew bundle"
run_brew_bundle "${JJR_HOME}/.config/Brewfile"

if ${HOME_ENV} ; then
    run_brew_bundle "${JJR_HOME}/.config/Brewfile.home"
fi

if ${WORK_ENV} ; then
    run_brew_bundle "${JJR_HOME}/.config/Brewfile.work"
fi


echo ""
echo "Setup done!"
echo ""
echo ""
echo "Other things to manully install and set up:"
echo
echo "- Set up external keyboard modifiers"
echo "- Set tab to focus all input controls in System Settings -> Keyboard -> Keyboard Navigation"
echo "- customize date and time format - 24h, short date YYYY-MM-DD. System Settings -> General -> Date Time"
echo "- Enable three finger trackpad dragging in Accessibility -> Mouse & Tracking Mouse https://support.apple.com/en-us/HT204609"
echo "- Set iTerm preferences folder to ${JJR_HOME}/.config/iterm2. Be sure to set 'Save Changes' to Manual until you quit and have it load the old prefs or they will get clobbered"
echo "- Set Alfred preferences folder to ${JJR_HOME}/.config/alfred"
echo "- Give hammerspoon access to move around windows in Security & Privacy properties Accessibility"
echo "- Set Alfred activation key - https://mail.google.com/mail/u/0/#search/alfred+power+pack/FMfcgxwCgphtpDPXWfsZClWlfWTQWRxM"
echo "- Give Alfred Snippets Accessibility access. First enable snippets in the Alfred preferences, then follow instructions"
echo "- Todoist needs to be installed from the App Store"
echo "- Give emacs full disk access in Privacy https://medium.com/@holzman.simon/emacs-on-macos-catalina-10-15-in-2019-79ff713c1ccc "
echo "- Downliad Elgato FaceCam 'Camera Hub' software - https://www.elgato.com/en/downloads"
echo ""
echo "Music software setup - https://docs.google.com/document/d/1vfKXBZr6PrctjJdxzqQ6CK69AZTAY1PvexdZD4MI2zg/edit"
echo ""
echo "Other apps you've found useful in the past"
echo "- Blackmagic Disk Speed Test - for testing USB drive and cable speeds"
echo 

if ${WORK_ENV} ; then
    echo "HubSpot setup"
    echo "Copy 'eng' directory over from old laptop"
    echo "Install latest Intellij CE using JetBrains Toolbox"
    echo "Launch Intellij and install plugins (hubspot, material theme)"
fi


chmod +x ${HOME}/./.bin/*
chmod +x ${HOME}/.tmux/plugins/tpm/tpm
# pushd ${HOME}/.tmux
# chmod +x $(find . -name *.sh -o -name *.tmux)
#popd
# If the above permission update doesn't work for tmux plugins it might be necessary to delete ~/.tmux/plugins and run
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Then prefix + I inside tmux to reinitialize plugins. i had some problems when moving to a new machine
# OK, twice now I had to do ^^. Not sure what the issue is but deleteing and recloning just works
# prefix + I shows no visible signs of doing anything so wait about 20 seconds

echo ""
echo "All done. Share and enjoy!"
