#!/bin/bash

function jjr-dialog ()
{
    if [ -e $(which zenity &> /dev/null) ] && [ -n "$DISPLAY" ]  ; then
	zenity --title "$1" --info --text "$2" > /dev/null 2>&1
    elif [ -e $(which xmessage &> /dev/null) ] && [ -n "$DISPLAY" ] ; then
	xmessage -bg black -fg green -bd white -center \
	    -buttons OK -default OK "$2" &> /dev/null
    else
	echo "$1: $2"
    fi
}


echo "*** Detecting display profile"
# running auto-disper will detect what display config is present
# and switch to that profile.  It will output what the profile is
# so that we can set other stuff like keyboard and mouse buttons
DISPLAY_PROFILE=$(auto-disper --change)
echo "*** Done detecting"
if [ $? -ne 0 ] ; then
    jjr-dialog "There was an error changing the display profile:\n $DISPLAY_PROFILE"
fi

if echo $DISPLAY_PROFILE | grep "laptop" ; then
    setup-mouse default
    toggle-alt-super-key.sh alt
elif echo $DISPLAY_PROFILE | grep "desk" ; then
    setup-mouse logitech
    toggle-alt-super-key.sh default
else
    echo "Unknown display profile. Using macbook settings"
    echo $DISPLAY_PROFILE
    setup-mouse default
    toggle-alt-super-key.sh alt
fi

echo "*** Update ip address in /etc/hosts file"
sudo /home/jorussel/Dropbox/jjr-environment/bin/update-linux-ipaddress

# turns off the red light in the audio jack
echo "*** Shutting off digital audio input"
amixer set IEC958 off

# its just not right sometimes
echo "*** Restarting xbindkeys"
pkill xbindkeys
cd
xbindkeys